/*
LedgerX Public API

## Introduction  The LedgerX API provides endpoints for synchronizing on-chain wallets, retrieving normalized financial transactions, and managing wallets, wallet groups, organization members, and the accounting system (Chart of Accounts).  - **Security**: All endpoints (unless otherwise specified) require an **API_KEY**   in the request header. - **Rate Limit**: Depends on the user’s subscription plan. See details on the   subscriptions page. - **Compute Unit (CU)**: Each API consumes a specific number of CUs, which are   deducted from your monthly total.  **Useful Links**: - Rate limit: https://ledgerx.finance/subscriptions - Compute Unit: https://ledgerx.finance/subscriptions  > Note: Some CU and rate limit descriptions are for documentation purposes only. Actual limits are applied based on the user’s subscription plan. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateChartOfAccountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateChartOfAccountRequest{}

// UpdateChartOfAccountRequest struct for UpdateChartOfAccountRequest
type UpdateChartOfAccountRequest struct {
	Code string `json:"code"`
	Name string `json:"name"`
	Type string `json:"type"`
	Description *string `json:"description,omitempty"`
}

type _UpdateChartOfAccountRequest UpdateChartOfAccountRequest

// NewUpdateChartOfAccountRequest instantiates a new UpdateChartOfAccountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateChartOfAccountRequest(code string, name string, type_ string) *UpdateChartOfAccountRequest {
	this := UpdateChartOfAccountRequest{}
	this.Code = code
	this.Name = name
	this.Type = type_
	return &this
}

// NewUpdateChartOfAccountRequestWithDefaults instantiates a new UpdateChartOfAccountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateChartOfAccountRequestWithDefaults() *UpdateChartOfAccountRequest {
	this := UpdateChartOfAccountRequest{}
	return &this
}

// GetCode returns the Code field value
func (o *UpdateChartOfAccountRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *UpdateChartOfAccountRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *UpdateChartOfAccountRequest) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *UpdateChartOfAccountRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateChartOfAccountRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateChartOfAccountRequest) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *UpdateChartOfAccountRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateChartOfAccountRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateChartOfAccountRequest) SetType(v string) {
	o.Type = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateChartOfAccountRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateChartOfAccountRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateChartOfAccountRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateChartOfAccountRequest) SetDescription(v string) {
	o.Description = &v
}

func (o UpdateChartOfAccountRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateChartOfAccountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *UpdateChartOfAccountRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateChartOfAccountRequest := _UpdateChartOfAccountRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateChartOfAccountRequest)

	if err != nil {
		return err
	}

	*o = UpdateChartOfAccountRequest(varUpdateChartOfAccountRequest)

	return err
}

type NullableUpdateChartOfAccountRequest struct {
	value *UpdateChartOfAccountRequest
	isSet bool
}

func (v NullableUpdateChartOfAccountRequest) Get() *UpdateChartOfAccountRequest {
	return v.value
}

func (v *NullableUpdateChartOfAccountRequest) Set(val *UpdateChartOfAccountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateChartOfAccountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateChartOfAccountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateChartOfAccountRequest(val *UpdateChartOfAccountRequest) *NullableUpdateChartOfAccountRequest {
	return &NullableUpdateChartOfAccountRequest{value: val, isSet: true}
}

func (v NullableUpdateChartOfAccountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateChartOfAccountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


