/*
LedgerX Public API

## Introduction  The LedgerX API provides endpoints for synchronizing on-chain wallets, retrieving normalized financial transactions, and managing wallets, wallet groups, organization members, and the accounting system (Chart of Accounts).  - **Security**: All endpoints (unless otherwise specified) require an **API_KEY**   in the request header. - **Rate Limit**: Depends on the user’s subscription plan. See details on the   subscriptions page. - **Compute Unit (CU)**: Each API consumes a specific number of CUs, which are   deducted from your monthly total.  **Useful Links**: - Rate limit: https://ledgerx.finance/subscriptions - Compute Unit: https://ledgerx.finance/subscriptions  > Note: Some CU and rate limit descriptions are for documentation purposes only. Actual limits are applied based on the user’s subscription plan. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateWalletGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateWalletGroupRequest{}

// UpdateWalletGroupRequest struct for UpdateWalletGroupRequest
type UpdateWalletGroupRequest struct {
	Name string `json:"name"`
}

type _UpdateWalletGroupRequest UpdateWalletGroupRequest

// NewUpdateWalletGroupRequest instantiates a new UpdateWalletGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateWalletGroupRequest(name string) *UpdateWalletGroupRequest {
	this := UpdateWalletGroupRequest{}
	this.Name = name
	return &this
}

// NewUpdateWalletGroupRequestWithDefaults instantiates a new UpdateWalletGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateWalletGroupRequestWithDefaults() *UpdateWalletGroupRequest {
	this := UpdateWalletGroupRequest{}
	return &this
}

// GetName returns the Name field value
func (o *UpdateWalletGroupRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateWalletGroupRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateWalletGroupRequest) SetName(v string) {
	o.Name = v
}

func (o UpdateWalletGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateWalletGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *UpdateWalletGroupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateWalletGroupRequest := _UpdateWalletGroupRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateWalletGroupRequest)

	if err != nil {
		return err
	}

	*o = UpdateWalletGroupRequest(varUpdateWalletGroupRequest)

	return err
}

type NullableUpdateWalletGroupRequest struct {
	value *UpdateWalletGroupRequest
	isSet bool
}

func (v NullableUpdateWalletGroupRequest) Get() *UpdateWalletGroupRequest {
	return v.value
}

func (v *NullableUpdateWalletGroupRequest) Set(val *UpdateWalletGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateWalletGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateWalletGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateWalletGroupRequest(val *UpdateWalletGroupRequest) *NullableUpdateWalletGroupRequest {
	return &NullableUpdateWalletGroupRequest{value: val, isSet: true}
}

func (v NullableUpdateWalletGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateWalletGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


