/*
LedgerX Public API

## Introduction  The LedgerX API provides endpoints for synchronizing on-chain wallets, retrieving normalized financial transactions, and managing wallets, wallet groups, organization members, and the accounting system (Chart of Accounts).  - **Security**: All endpoints (unless otherwise specified) require an **API_KEY**   in the request header. - **Rate Limit**: Depends on the user’s subscription plan. See details on the   subscriptions page. - **Compute Unit (CU)**: Each API consumes a specific number of CUs, which are   deducted from your monthly total.  **Useful Links**: - Rate limit: https://ledgerx.finance/subscriptions - Compute Unit: https://ledgerx.finance/subscriptions  > Note: Some CU and rate limit descriptions are for documentation purposes only. Actual limits are applied based on the user’s subscription plan. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerx

import (
	"encoding/json"
)

// checks if the ImportWallets200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportWallets200Response{}

// ImportWallets200Response struct for ImportWallets200Response
type ImportWallets200Response struct {
	JobIds []string `json:"jobIds,omitempty"`
}

// NewImportWallets200Response instantiates a new ImportWallets200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportWallets200Response() *ImportWallets200Response {
	this := ImportWallets200Response{}
	return &this
}

// NewImportWallets200ResponseWithDefaults instantiates a new ImportWallets200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportWallets200ResponseWithDefaults() *ImportWallets200Response {
	this := ImportWallets200Response{}
	return &this
}

// GetJobIds returns the JobIds field value if set, zero value otherwise.
func (o *ImportWallets200Response) GetJobIds() []string {
	if o == nil || IsNil(o.JobIds) {
		var ret []string
		return ret
	}
	return o.JobIds
}

// GetJobIdsOk returns a tuple with the JobIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportWallets200Response) GetJobIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.JobIds) {
		return nil, false
	}
	return o.JobIds, true
}

// HasJobIds returns a boolean if a field has been set.
func (o *ImportWallets200Response) HasJobIds() bool {
	if o != nil && !IsNil(o.JobIds) {
		return true
	}

	return false
}

// SetJobIds gets a reference to the given []string and assigns it to the JobIds field.
func (o *ImportWallets200Response) SetJobIds(v []string) {
	o.JobIds = v
}

func (o ImportWallets200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportWallets200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JobIds) {
		toSerialize["jobIds"] = o.JobIds
	}
	return toSerialize, nil
}

type NullableImportWallets200Response struct {
	value *ImportWallets200Response
	isSet bool
}

func (v NullableImportWallets200Response) Get() *ImportWallets200Response {
	return v.value
}

func (v *NullableImportWallets200Response) Set(val *ImportWallets200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableImportWallets200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableImportWallets200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportWallets200Response(val *ImportWallets200Response) *NullableImportWallets200Response {
	return &NullableImportWallets200Response{value: val, isSet: true}
}

func (v NullableImportWallets200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportWallets200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


