/*
LedgerX Public API

## Introduction  The LedgerX API provides endpoints for synchronizing on-chain wallets, retrieving normalized financial transactions, and managing wallets, wallet groups, organization members, and the accounting system (Chart of Accounts).  - **Security**: All endpoints (unless otherwise specified) require an **API_KEY**   in the request header. - **Rate Limit**: Depends on the user’s subscription plan. See details on the   subscriptions page. - **Compute Unit (CU)**: Each API consumes a specific number of CUs, which are   deducted from your monthly total.  **Useful Links**: - Rate limit: https://ledgerx.finance/subscriptions - Compute Unit: https://ledgerx.finance/subscriptions  > Note: Some CU and rate limit descriptions are for documentation purposes only. Actual limits are applied based on the user’s subscription plan. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerx

import (
	"encoding/json"
)

// checks if the ListMembers200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListMembers200Response{}

// ListMembers200Response struct for ListMembers200Response
type ListMembers200Response struct {
	Data *ListMembers200ResponseData `json:"data,omitempty"`
}

// NewListMembers200Response instantiates a new ListMembers200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListMembers200Response() *ListMembers200Response {
	this := ListMembers200Response{}
	return &this
}

// NewListMembers200ResponseWithDefaults instantiates a new ListMembers200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListMembers200ResponseWithDefaults() *ListMembers200Response {
	this := ListMembers200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListMembers200Response) GetData() ListMembers200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret ListMembers200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMembers200Response) GetDataOk() (*ListMembers200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListMembers200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ListMembers200ResponseData and assigns it to the Data field.
func (o *ListMembers200Response) SetData(v ListMembers200ResponseData) {
	o.Data = &v
}

func (o ListMembers200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListMembers200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableListMembers200Response struct {
	value *ListMembers200Response
	isSet bool
}

func (v NullableListMembers200Response) Get() *ListMembers200Response {
	return v.value
}

func (v *NullableListMembers200Response) Set(val *ListMembers200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListMembers200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListMembers200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListMembers200Response(val *ListMembers200Response) *NullableListMembers200Response {
	return &NullableListMembers200Response{value: val, isSet: true}
}

func (v NullableListMembers200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListMembers200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


