/*
LedgerX Public API

## Introduction  The LedgerX API provides endpoints for synchronizing on-chain wallets, retrieving normalized financial transactions, and managing wallets, wallet groups, organization members, and the accounting system (Chart of Accounts).  - **Security**: All endpoints (unless otherwise specified) require an **API_KEY**   in the request header. - **Rate Limit**: Depends on the user’s subscription plan. See details on the   subscriptions page. - **Compute Unit (CU)**: Each API consumes a specific number of CUs, which are   deducted from your monthly total.  **Useful Links**: - Rate limit: https://ledgerx.finance/subscriptions - Compute Unit: https://ledgerx.finance/subscriptions  > Note: Some CU and rate limit descriptions are for documentation purposes only. Actual limits are applied based on the user’s subscription plan. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SyncPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncPutRequest{}

// SyncPutRequest struct for SyncPutRequest
type SyncPutRequest struct {
	Action string `json:"action"`
}

type _SyncPutRequest SyncPutRequest

// NewSyncPutRequest instantiates a new SyncPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncPutRequest(action string) *SyncPutRequest {
	this := SyncPutRequest{}
	this.Action = action
	return &this
}

// NewSyncPutRequestWithDefaults instantiates a new SyncPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncPutRequestWithDefaults() *SyncPutRequest {
	this := SyncPutRequest{}
	return &this
}

// GetAction returns the Action field value
func (o *SyncPutRequest) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *SyncPutRequest) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *SyncPutRequest) SetAction(v string) {
	o.Action = v
}

func (o SyncPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	return toSerialize, nil
}

func (o *SyncPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSyncPutRequest := _SyncPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSyncPutRequest)

	if err != nil {
		return err
	}

	*o = SyncPutRequest(varSyncPutRequest)

	return err
}

type NullableSyncPutRequest struct {
	value *SyncPutRequest
	isSet bool
}

func (v NullableSyncPutRequest) Get() *SyncPutRequest {
	return v.value
}

func (v *NullableSyncPutRequest) Set(val *SyncPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncPutRequest(val *SyncPutRequest) *NullableSyncPutRequest {
	return &NullableSyncPutRequest{value: val, isSet: true}
}

func (v NullableSyncPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


