/*
LedgerX Public API

## Introduction  The LedgerX API provides endpoints for synchronizing on-chain wallets, retrieving normalized financial transactions, and managing wallets, wallet groups, organization members, and the accounting system (Chart of Accounts).  - **Security**: All endpoints (unless otherwise specified) require an **API_KEY**   in the request header. - **Rate Limit**: Depends on the user’s subscription plan. See details on the   subscriptions page. - **Compute Unit (CU)**: Each API consumes a specific number of CUs, which are   deducted from your monthly total.  **Useful Links**: - Rate limit: https://ledgerx.finance/subscriptions - Compute Unit: https://ledgerx.finance/subscriptions  > Note: Some CU and rate limit descriptions are for documentation purposes only. Actual limits are applied based on the user’s subscription plan. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerx

import (
	"encoding/json"
)

// checks if the FinancialTransactionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FinancialTransactionsResponse{}

// FinancialTransactionsResponse struct for FinancialTransactionsResponse
type FinancialTransactionsResponse struct {
	Data *FinancialTransactionsResponseData `json:"data,omitempty"`
}

// NewFinancialTransactionsResponse instantiates a new FinancialTransactionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFinancialTransactionsResponse() *FinancialTransactionsResponse {
	this := FinancialTransactionsResponse{}
	return &this
}

// NewFinancialTransactionsResponseWithDefaults instantiates a new FinancialTransactionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFinancialTransactionsResponseWithDefaults() *FinancialTransactionsResponse {
	this := FinancialTransactionsResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FinancialTransactionsResponse) GetData() FinancialTransactionsResponseData {
	if o == nil || IsNil(o.Data) {
		var ret FinancialTransactionsResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinancialTransactionsResponse) GetDataOk() (*FinancialTransactionsResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FinancialTransactionsResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given FinancialTransactionsResponseData and assigns it to the Data field.
func (o *FinancialTransactionsResponse) SetData(v FinancialTransactionsResponseData) {
	o.Data = &v
}

func (o FinancialTransactionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FinancialTransactionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFinancialTransactionsResponse struct {
	value *FinancialTransactionsResponse
	isSet bool
}

func (v NullableFinancialTransactionsResponse) Get() *FinancialTransactionsResponse {
	return v.value
}

func (v *NullableFinancialTransactionsResponse) Set(val *FinancialTransactionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFinancialTransactionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFinancialTransactionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinancialTransactionsResponse(val *FinancialTransactionsResponse) *NullableFinancialTransactionsResponse {
	return &NullableFinancialTransactionsResponse{value: val, isSet: true}
}

func (v NullableFinancialTransactionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinancialTransactionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


