/*
LedgerX Public API

## Introduction  The LedgerX API provides endpoints for synchronizing on-chain wallets, retrieving normalized financial transactions, and managing wallets, wallet groups, organization members, and the accounting system (Chart of Accounts).  - **Security**: All endpoints (unless otherwise specified) require an **API_KEY**   in the request header. - **Rate Limit**: Depends on the user’s subscription plan. See details on the   subscriptions page. - **Compute Unit (CU)**: Each API consumes a specific number of CUs, which are   deducted from your monthly total.  **Useful Links**: - Rate limit: https://ledgerx.finance/subscriptions - Compute Unit: https://ledgerx.finance/subscriptions  > Note: Some CU and rate limit descriptions are for documentation purposes only. Actual limits are applied based on the user’s subscription plan. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerx

import (
	"encoding/json"
)

// checks if the ListChartOfAccounts200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListChartOfAccounts200Response{}

// ListChartOfAccounts200Response struct for ListChartOfAccounts200Response
type ListChartOfAccounts200Response struct {
	Data []ListChartOfAccounts200ResponseDataInner `json:"data,omitempty"`
}

// NewListChartOfAccounts200Response instantiates a new ListChartOfAccounts200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListChartOfAccounts200Response() *ListChartOfAccounts200Response {
	this := ListChartOfAccounts200Response{}
	return &this
}

// NewListChartOfAccounts200ResponseWithDefaults instantiates a new ListChartOfAccounts200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListChartOfAccounts200ResponseWithDefaults() *ListChartOfAccounts200Response {
	this := ListChartOfAccounts200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListChartOfAccounts200Response) GetData() []ListChartOfAccounts200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []ListChartOfAccounts200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListChartOfAccounts200Response) GetDataOk() ([]ListChartOfAccounts200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListChartOfAccounts200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ListChartOfAccounts200ResponseDataInner and assigns it to the Data field.
func (o *ListChartOfAccounts200Response) SetData(v []ListChartOfAccounts200ResponseDataInner) {
	o.Data = v
}

func (o ListChartOfAccounts200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListChartOfAccounts200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableListChartOfAccounts200Response struct {
	value *ListChartOfAccounts200Response
	isSet bool
}

func (v NullableListChartOfAccounts200Response) Get() *ListChartOfAccounts200Response {
	return v.value
}

func (v *NullableListChartOfAccounts200Response) Set(val *ListChartOfAccounts200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListChartOfAccounts200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListChartOfAccounts200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListChartOfAccounts200Response(val *ListChartOfAccounts200Response) *NullableListChartOfAccounts200Response {
	return &NullableListChartOfAccounts200Response{value: val, isSet: true}
}

func (v NullableListChartOfAccounts200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListChartOfAccounts200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


