/*
LedgerX Public API

## Introduction  The LedgerX API provides endpoints for synchronizing on-chain wallets, retrieving normalized financial transactions, and managing wallets, wallet groups, organization members, and the accounting system (Chart of Accounts).  - **Security**: All endpoints (unless otherwise specified) require an **API_KEY**   in the request header. - **Rate Limit**: Depends on the user’s subscription plan. See details on the   subscriptions page. - **Compute Unit (CU)**: Each API consumes a specific number of CUs, which are   deducted from your monthly total.  **Useful Links**: - Rate limit: https://ledgerx.finance/subscriptions - Compute Unit: https://ledgerx.finance/subscriptions  > Note: Some CU and rate limit descriptions are for documentation purposes only. Actual limits are applied based on the user’s subscription plan. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SyncPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncPostRequest{}

// SyncPostRequest struct for SyncPostRequest
type SyncPostRequest struct {
	WalletId string `json:"walletId"`
}

type _SyncPostRequest SyncPostRequest

// NewSyncPostRequest instantiates a new SyncPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncPostRequest(walletId string) *SyncPostRequest {
	this := SyncPostRequest{}
	this.WalletId = walletId
	return &this
}

// NewSyncPostRequestWithDefaults instantiates a new SyncPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncPostRequestWithDefaults() *SyncPostRequest {
	this := SyncPostRequest{}
	return &this
}

// GetWalletId returns the WalletId field value
func (o *SyncPostRequest) GetWalletId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WalletId
}

// GetWalletIdOk returns a tuple with the WalletId field value
// and a boolean to check if the value has been set.
func (o *SyncPostRequest) GetWalletIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletId, true
}

// SetWalletId sets field value
func (o *SyncPostRequest) SetWalletId(v string) {
	o.WalletId = v
}

func (o SyncPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["walletId"] = o.WalletId
	return toSerialize, nil
}

func (o *SyncPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"walletId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSyncPostRequest := _SyncPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSyncPostRequest)

	if err != nil {
		return err
	}

	*o = SyncPostRequest(varSyncPostRequest)

	return err
}

type NullableSyncPostRequest struct {
	value *SyncPostRequest
	isSet bool
}

func (v NullableSyncPostRequest) Get() *SyncPostRequest {
	return v.value
}

func (v *NullableSyncPostRequest) Set(val *SyncPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncPostRequest(val *SyncPostRequest) *NullableSyncPostRequest {
	return &NullableSyncPostRequest{value: val, isSet: true}
}

func (v NullableSyncPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


