/*
LedgerX Public API

## Introduction  The LedgerX API provides endpoints for synchronizing on-chain wallets, retrieving normalized financial transactions, and managing wallets, wallet groups, organization members, and the accounting system (Chart of Accounts).  - **Security**: All endpoints (unless otherwise specified) require an **API_KEY**   in the request header. - **Rate Limit**: Depends on the user’s subscription plan. See details on the   subscriptions page. - **Compute Unit (CU)**: Each API consumes a specific number of CUs, which are   deducted from your monthly total.  **Useful Links**: - Rate limit: https://ledgerx.finance/subscriptions - Compute Unit: https://ledgerx.finance/subscriptions  > Note: Some CU and rate limit descriptions are for documentation purposes only. Actual limits are applied based on the user’s subscription plan. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerx

import (
	"encoding/json"
)

// checks if the FinancialTransactionTypeDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FinancialTransactionTypeDetail{}

// FinancialTransactionTypeDetail struct for FinancialTransactionTypeDetail
type FinancialTransactionTypeDetail struct {
	Value *string `json:"value,omitempty"`
	Label *string `json:"label,omitempty"`
}

// NewFinancialTransactionTypeDetail instantiates a new FinancialTransactionTypeDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFinancialTransactionTypeDetail() *FinancialTransactionTypeDetail {
	this := FinancialTransactionTypeDetail{}
	return &this
}

// NewFinancialTransactionTypeDetailWithDefaults instantiates a new FinancialTransactionTypeDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFinancialTransactionTypeDetailWithDefaults() *FinancialTransactionTypeDetail {
	this := FinancialTransactionTypeDetail{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *FinancialTransactionTypeDetail) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinancialTransactionTypeDetail) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *FinancialTransactionTypeDetail) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *FinancialTransactionTypeDetail) SetValue(v string) {
	o.Value = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *FinancialTransactionTypeDetail) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinancialTransactionTypeDetail) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *FinancialTransactionTypeDetail) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *FinancialTransactionTypeDetail) SetLabel(v string) {
	o.Label = &v
}

func (o FinancialTransactionTypeDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FinancialTransactionTypeDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

type NullableFinancialTransactionTypeDetail struct {
	value *FinancialTransactionTypeDetail
	isSet bool
}

func (v NullableFinancialTransactionTypeDetail) Get() *FinancialTransactionTypeDetail {
	return v.value
}

func (v *NullableFinancialTransactionTypeDetail) Set(val *FinancialTransactionTypeDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableFinancialTransactionTypeDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableFinancialTransactionTypeDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinancialTransactionTypeDetail(val *FinancialTransactionTypeDetail) *NullableFinancialTransactionTypeDetail {
	return &NullableFinancialTransactionTypeDetail{value: val, isSet: true}
}

func (v NullableFinancialTransactionTypeDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinancialTransactionTypeDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


