/*
LedgerX Public API

## Introduction  The LedgerX API provides endpoints for synchronizing on-chain wallets, retrieving normalized financial transactions, and managing wallets, wallet groups, organization members, and the accounting system (Chart of Accounts).  - **Security**: All endpoints (unless otherwise specified) require an **API_KEY**   in the request header. - **Rate Limit**: Depends on the user’s subscription plan. See details on the   subscriptions page. - **Compute Unit (CU)**: Each API consumes a specific number of CUs, which are   deducted from your monthly total.  **Useful Links**: - Rate limit: https://ledgerx.finance/subscriptions - Compute Unit: https://ledgerx.finance/subscriptions  > Note: Some CU and rate limit descriptions are for documentation purposes only. Actual limits are applied based on the user’s subscription plan. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerx

import (
	"encoding/json"
)

// checks if the ListCoaMappings200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCoaMappings200Response{}

// ListCoaMappings200Response struct for ListCoaMappings200Response
type ListCoaMappings200Response struct {
	Data []ChartOfAccountMapping `json:"data,omitempty"`
}

// NewListCoaMappings200Response instantiates a new ListCoaMappings200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCoaMappings200Response() *ListCoaMappings200Response {
	this := ListCoaMappings200Response{}
	return &this
}

// NewListCoaMappings200ResponseWithDefaults instantiates a new ListCoaMappings200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCoaMappings200ResponseWithDefaults() *ListCoaMappings200Response {
	this := ListCoaMappings200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListCoaMappings200Response) GetData() []ChartOfAccountMapping {
	if o == nil || IsNil(o.Data) {
		var ret []ChartOfAccountMapping
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCoaMappings200Response) GetDataOk() ([]ChartOfAccountMapping, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListCoaMappings200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ChartOfAccountMapping and assigns it to the Data field.
func (o *ListCoaMappings200Response) SetData(v []ChartOfAccountMapping) {
	o.Data = v
}

func (o ListCoaMappings200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCoaMappings200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableListCoaMappings200Response struct {
	value *ListCoaMappings200Response
	isSet bool
}

func (v NullableListCoaMappings200Response) Get() *ListCoaMappings200Response {
	return v.value
}

func (v *NullableListCoaMappings200Response) Set(val *ListCoaMappings200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListCoaMappings200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListCoaMappings200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCoaMappings200Response(val *ListCoaMappings200Response) *NullableListCoaMappings200Response {
	return &NullableListCoaMappings200Response{value: val, isSet: true}
}

func (v NullableListCoaMappings200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCoaMappings200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


