/*
LedgerX Public API

## Introduction  The LedgerX API provides endpoints for synchronizing on-chain wallets, retrieving normalized financial transactions, and managing wallets, wallet groups, organization members, and the accounting system (Chart of Accounts).  - **Security**: All endpoints (unless otherwise specified) require an **API_KEY**   in the request header. - **Rate Limit**: Depends on the user’s subscription plan. See details on the   subscriptions page. - **Compute Unit (CU)**: Each API consumes a specific number of CUs, which are   deducted from your monthly total.  **Useful Links**: - Rate limit: https://ledgerx.finance/subscriptions - Compute Unit: https://ledgerx.finance/subscriptions  > Note: Some CU and rate limit descriptions are for documentation purposes only. Actual limits are applied based on the user’s subscription plan. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerx

import (
	"encoding/json"
)

// checks if the WalletListResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WalletListResponseData{}

// WalletListResponseData struct for WalletListResponseData
type WalletListResponseData struct {
	Items []Wallet `json:"items,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

// NewWalletListResponseData instantiates a new WalletListResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletListResponseData() *WalletListResponseData {
	this := WalletListResponseData{}
	return &this
}

// NewWalletListResponseDataWithDefaults instantiates a new WalletListResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletListResponseDataWithDefaults() *WalletListResponseData {
	this := WalletListResponseData{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *WalletListResponseData) GetItems() []Wallet {
	if o == nil || IsNil(o.Items) {
		var ret []Wallet
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletListResponseData) GetItemsOk() ([]Wallet, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *WalletListResponseData) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Wallet and assigns it to the Items field.
func (o *WalletListResponseData) SetItems(v []Wallet) {
	o.Items = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *WalletListResponseData) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletListResponseData) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *WalletListResponseData) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *WalletListResponseData) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o WalletListResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WalletListResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableWalletListResponseData struct {
	value *WalletListResponseData
	isSet bool
}

func (v NullableWalletListResponseData) Get() *WalletListResponseData {
	return v.value
}

func (v *NullableWalletListResponseData) Set(val *WalletListResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletListResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletListResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletListResponseData(val *WalletListResponseData) *NullableWalletListResponseData {
	return &NullableWalletListResponseData{value: val, isSet: true}
}

func (v NullableWalletListResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletListResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


