/*
LedgerX Public API

## Introduction  The LedgerX API provides endpoints for synchronizing on-chain wallets, retrieving normalized financial transactions, and managing wallets, wallet groups, organization members, and the accounting system (Chart of Accounts).  - **Security**: All endpoints (unless otherwise specified) require an **API_KEY**   in the request header. - **Rate Limit**: Depends on the user’s subscription plan. See details on the   subscriptions page. - **Compute Unit (CU)**: Each API consumes a specific number of CUs, which are   deducted from your monthly total.  **Useful Links**: - Rate limit: https://ledgerx.finance/subscriptions - Compute Unit: https://ledgerx.finance/subscriptions  > Note: Some CU and rate limit descriptions are for documentation purposes only. Actual limits are applied based on the user’s subscription plan. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerx

import (
	"encoding/json"
)

// checks if the CreateChartOfAccount201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateChartOfAccount201Response{}

// CreateChartOfAccount201Response struct for CreateChartOfAccount201Response
type CreateChartOfAccount201Response struct {
	Data *ListChartOfAccounts200ResponseDataInner `json:"data,omitempty"`
}

// NewCreateChartOfAccount201Response instantiates a new CreateChartOfAccount201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateChartOfAccount201Response() *CreateChartOfAccount201Response {
	this := CreateChartOfAccount201Response{}
	return &this
}

// NewCreateChartOfAccount201ResponseWithDefaults instantiates a new CreateChartOfAccount201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateChartOfAccount201ResponseWithDefaults() *CreateChartOfAccount201Response {
	this := CreateChartOfAccount201Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateChartOfAccount201Response) GetData() ListChartOfAccounts200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret ListChartOfAccounts200ResponseDataInner
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateChartOfAccount201Response) GetDataOk() (*ListChartOfAccounts200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateChartOfAccount201Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ListChartOfAccounts200ResponseDataInner and assigns it to the Data field.
func (o *CreateChartOfAccount201Response) SetData(v ListChartOfAccounts200ResponseDataInner) {
	o.Data = &v
}

func (o CreateChartOfAccount201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateChartOfAccount201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreateChartOfAccount201Response struct {
	value *CreateChartOfAccount201Response
	isSet bool
}

func (v NullableCreateChartOfAccount201Response) Get() *CreateChartOfAccount201Response {
	return v.value
}

func (v *NullableCreateChartOfAccount201Response) Set(val *CreateChartOfAccount201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateChartOfAccount201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateChartOfAccount201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateChartOfAccount201Response(val *CreateChartOfAccount201Response) *NullableCreateChartOfAccount201Response {
	return &NullableCreateChartOfAccount201Response{value: val, isSet: true}
}

func (v NullableCreateChartOfAccount201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateChartOfAccount201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


