/*
LedgerX Public API

## Introduction  The LedgerX API provides endpoints for synchronizing on-chain wallets, retrieving normalized financial transactions, and managing wallets, wallet groups, organization members, and the accounting system (Chart of Accounts).  - **Security**: All endpoints (unless otherwise specified) require an **API_KEY**   in the request header. - **Rate Limit**: Depends on the user’s subscription plan. See details on the   subscriptions page. - **Compute Unit (CU)**: Each API consumes a specific number of CUs, which are   deducted from your monthly total.  **Useful Links**: - Rate limit: https://ledgerx.finance/subscriptions - Compute Unit: https://ledgerx.finance/subscriptions  > Note: Some CU and rate limit descriptions are for documentation purposes only. Actual limits are applied based on the user’s subscription plan. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerx

import (
	"encoding/json"
)

// checks if the WalletListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WalletListResponse{}

// WalletListResponse struct for WalletListResponse
type WalletListResponse struct {
	Data *WalletListResponseData `json:"data,omitempty"`
}

// NewWalletListResponse instantiates a new WalletListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletListResponse() *WalletListResponse {
	this := WalletListResponse{}
	return &this
}

// NewWalletListResponseWithDefaults instantiates a new WalletListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletListResponseWithDefaults() *WalletListResponse {
	this := WalletListResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *WalletListResponse) GetData() WalletListResponseData {
	if o == nil || IsNil(o.Data) {
		var ret WalletListResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletListResponse) GetDataOk() (*WalletListResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *WalletListResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given WalletListResponseData and assigns it to the Data field.
func (o *WalletListResponse) SetData(v WalletListResponseData) {
	o.Data = &v
}

func (o WalletListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WalletListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableWalletListResponse struct {
	value *WalletListResponse
	isSet bool
}

func (v NullableWalletListResponse) Get() *WalletListResponse {
	return v.value
}

func (v *NullableWalletListResponse) Set(val *WalletListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletListResponse(val *WalletListResponse) *NullableWalletListResponse {
	return &NullableWalletListResponse{value: val, isSet: true}
}

func (v NullableWalletListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


