version: '3.1'

services:

  db:
    image: postgres:14
    command: "-c logging_collector=on -c max_connections=500"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
