version: "3.8"
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "4566:4566"
    volumes:
      - ./aws:/etc/localstack/init/ready.d
    environment:
      SERVICES: s3
      DEBUG: 1
