/*
LedgerX Public API

Testing ChartOfAccountsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package ledgerx

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_ledgerx_ChartOfAccountsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ChartOfAccountsAPIService CreateChartOfAccount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ChartOfAccountsAPI.CreateChartOfAccount(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChartOfAccountsAPIService ListChartOfAccounts", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ChartOfAccountsAPI.ListChartOfAccounts(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChartOfAccountsAPIService ListCoaMappings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ChartOfAccountsAPI.ListCoaMappings(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChartOfAccountsAPIService UpdateChartOfAccount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var coaId string

		httpRes, err := apiClient.ChartOfAccountsAPI.UpdateChartOfAccount(context.Background(), coaId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
