version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: ingestor_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ${INIT_DB_QUERY}:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: ingestor_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ingestor_worker
    restart: always
    env_file:
      - ./.env.docker
    environment:
      ACTION: worker
    depends_on:
      - postgres
      - redis

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ingestor_api
    restart: always
    env_file:
      - ./.env.docker
    environment:
      ACTION: api
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - postgres
      - redis
